### ISSUE TITLE
compiling file browser from source on macos

### ISSUE THREAD

**Issue by ipatch** [johanhelsing/qt-csd-demo#6]
I have little to no experience working with QT, but wanted to try and run the filebrowser example from this repo.  I ended up cloning the repo, and then tried running the below command from within the filebrowser directory.

```shell
qmake
```

and got the below error message

```shell
Project WARNING: Qt requires at least version 10.14 of the platform SDK, you're building against version 10.13. Please upgrade.
```

I'm running qmake from the version of QT installed via brew

```shell
brew install qt
```

I'm running macOS 10.13 with Xcode 10.1 installed.

```shell
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.13.6
BuildVersion:   17G12034
```

```shell
brew info qt
qt: stable 5.14.1 (bottled), HEAD [keg-only]
Cross-platform application and UI framework
https://www.qt.io/
/usr/local/Cellar/qt/5.14.1 (10,389 files, 363.1MB) *
  Poured from bottle on 2020-01-29 at 10:31:24
From: https://github.com/ipatch/homebrew-core/blob/master/Formula/qt.rb
```

Is it possible to run the filebrowser demo on macOS 10.13 or am I barking up the wrong tree?  I read and tried [this](https://forum.qt.io/topic/95127/install-from-scratch-new-empty-project-won-t-compile/16) but got the same error message.

**Comment by johanhelsing** [comment]
Yes, it should run on macOS.

But I don't have much experience with macOS, and can't comment on the versions. Also, generally it's best to install Qt using the official installer. Especially if you want to try out new-ish features.

Closing since there isn't really anything I can fix in this repo, should perhaps report this on the brew package, if you can't use Qt at all?
